/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by informer-gen

package v1

import (
	versioned "operator/pkg/kubernetes-actors/clientset/versioned"
	internalinterfaces "operator/pkg/kubernetes-actors/informers/externalversions/internalinterfaces"
	v1 "operator/pkg/kubernetes-actors/listers/quobyte/v1"
	time "time"

	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	quobyte_com_v1 "operator/pkg/api/quobyte.com/v1"
)

// QuobyteClientInformer provides access to a shared informer and lister for
// QuobyteClients.
type QuobyteClientInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.QuobyteClientLister
}

type quobyteClientInformer struct {
	factory internalinterfaces.SharedInformerFactory
}

// NewQuobyteClientInformer constructs a new informer for QuobyteClient type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewQuobyteClientInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options meta_v1.ListOptions) (runtime.Object, error) {
				return client.QuobyteV1().QuobyteClients(namespace).List(options)
			},
			WatchFunc: func(options meta_v1.ListOptions) (watch.Interface, error) {
				return client.QuobyteV1().QuobyteClients(namespace).Watch(options)
			},
		},
		&quobyte_com_v1.QuobyteClient{},
		resyncPeriod,
		indexers,
	)
}

func defaultQuobyteClientInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewQuobyteClientInformer(client, meta_v1.NamespaceAll, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc})
}

func (f *quobyteClientInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&quobyte_com_v1.QuobyteClient{}, defaultQuobyteClientInformer)
}

func (f *quobyteClientInformer) Lister() v1.QuobyteClientLister {
	return v1.NewQuobyteClientLister(f.Informer().GetIndexer())
}
