/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by informer-gen

package v1

import (
	versioned "operator/pkg/kubernetes-actors/clientset/versioned"
	internalinterfaces "operator/pkg/kubernetes-actors/informers/externalversions/internalinterfaces"
	v1 "operator/pkg/kubernetes-actors/listers/quobyte/v1"
	time "time"

	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	quobyte_com_v1 "operator/pkg/api/quobyte.com/v1"
)

// QuobyteServiceInformer provides access to a shared informer and lister for
// QuobyteServices.
type QuobyteServiceInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.QuobyteServiceLister
}

type quobyteServiceInformer struct {
	factory internalinterfaces.SharedInformerFactory
}

// NewQuobyteServiceInformer constructs a new informer for QuobyteService type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewQuobyteServiceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options meta_v1.ListOptions) (runtime.Object, error) {
				return client.QuobyteV1().QuobyteServices(namespace).List(options)
			},
			WatchFunc: func(options meta_v1.ListOptions) (watch.Interface, error) {
				return client.QuobyteV1().QuobyteServices(namespace).Watch(options)
			},
		},
		&quobyte_com_v1.QuobyteService{},
		resyncPeriod,
		indexers,
	)
}

func defaultQuobyteServiceInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewQuobyteServiceInformer(client, meta_v1.NamespaceAll, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc})
}

func (f *quobyteServiceInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&quobyte_com_v1.QuobyteService{}, defaultQuobyteServiceInformer)
}

func (f *quobyteServiceInformer) Lister() v1.QuobyteServiceLister {
	return v1.NewQuobyteServiceLister(f.Informer().GetIndexer())
}
