/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by lister-gen

package v1

// QuobyteClientListerExpansion allows custom methods to be added to
// QuobyteClientLister.
type QuobyteClientListerExpansion interface{}

// QuobyteClientNamespaceListerExpansion allows custom methods to be added to
// QuobyteClientNamespaceLister.
type QuobyteClientNamespaceListerExpansion interface{}

// QuobyteServiceListerExpansion allows custom methods to be added to
// QuobyteServiceLister.
type QuobyteServiceListerExpansion interface{}

// QuobyteServiceNamespaceListerExpansion allows custom methods to be added to
// QuobyteServiceNamespaceLister.
type QuobyteServiceNamespaceListerExpansion interface{}
