#!/bin/bash

if [[ "$1" = "-h" || "$1" = "--help" ]]; then
echo ""
fi

if [[ $? -eq 0 && ! -z "$1" ]]; then
sudo docker build -t operator -f Dockerfile.scratch .
sudo docker run -it operator
OPERATOR_RUN_ID="$(sudo docker ps -l | grep 'operator' | awk '{print $1}')"
echo "pushing $OPERATOR_RUN_ID"
sudo docker commit "$OPERATOR_RUN_ID" "$1"
sudo docker push "$1"
else
CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o operator .
fi